# https://docs.docker.com/reference/dockerfile

FROM ubuntu:16.04									# Informar imagem base
RUN apt-get update && apt-get install nginx -y		# Comandos que serão executados nesse ambiente
COPY arquivo_teste /tmp/arquivo_teste				# Copiar arquivos do host para o container
CMD bash											# Informar qual comando será executado por padrão